### PR TITLE
pass through --manifest-path and --package

### LINKED ISSUE #21: Add support for `--manifest-path` and `--package` cargo flags
```
# cargo chef cook --release --recipe-path recipe.json -- --workspace

error: Found argument '--workspace' which wasn't expected, or isn't valid in this context

If you tried to supply `--workspace` as a PATTERN use `-- --workspace`

USAGE:
    cargo chef cook [FLAGS] [OPTIONS]

For more information try --help
```

Same with pretty much everything, i.e. `--features`, `--package`, etc.
What to do if I want to pre-cache a specific CI job?

### PR DESCRIPTION
**Pull request by alsuren**
I'm not sure how to test this.

Fixes #21

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -85,6 +85,13 @@ pub struct Cook {
     /// This is equivalent to specifying `--tests --benches --examples`.
     #[clap(long)]
     all_targets: bool,
+    /// Path to Cargo.toml
+    #[clap(long)]
+    manifest_path: Option<PathBuf>,
+    // FIXME: also support -p short option
```
Comment (LukeMathWalker) [inline src/main.rs:91]: You added that already I think?
